# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i_uxAJQ1EjMZbnzjvDknecCYwKf6NrPY
"""

# example of loading the fashion mnist dataset
import matplotlib.pyplot as plt
from keras.datasets import fashion_mnist
# load dataset
(trainX, trainy), (testX, testy) = fashion_mnist.load_data()
 
labels = {0 : 'T-shirt/top', 1 : 'Trouser', 2 : 'Pullover', 3 : 'Dress', 4 : 'Coat', 5 : 'Sandal', 6 : 'Shirt', 7 : 'Sneaker', 8 : 'Bag', 9 : 'Ankle boot'}
 
ind = []
for i in range(10):
  ind.append(trainy.tolist().index(i))
 
j=0
fig, ax = plt.subplots(1, 10, figsize = (20,20))
for i in ind:
  ax[j].imshow(trainX[i], cmap=pyplot.get_cmap('gray'))
  ax[j].set_title(labels[j], y = -0.4)
  ax[j].axis('off')
  j+=1
# show the figure
plt.show()
